import type { Match } from "../types"

// Datos de partidos para la aplicación
export const matches: Match[] = [
  // Jornada 38
  {
    id: "j38_athletic_barcelona",
    competition: "LaLiga",
    date: "25/05/2025",
    time: "18:30",
    homeTeam: { id: "athletic-club", name: "Athletic Club", logoUrl: "/team-logos/athletic-club.png" },
    awayTeam: { id: "barcelona", name: "FC Barcelona", logoUrl: "/team-logos/barcelona.png" },
    homeCornerAvg: 5.7,
    awayCornerAvg: 7.1,
    totalCornerAvg: 12.8,
    stadium: "San Mamés",
    status: "upcoming",
    matchday: 38,
  },
  {
    id: "j38_betis_valencia",
    competition: "LaLiga",
    date: "24/05/2025",
    time: "18:30",
    homeTeam: { id: "real-betis", name: "Real Betis", logoUrl: "/team-logos/real-betis.png" },
    awayTeam: { id: "valencia-cf", name: "Valencia CF", logoUrl: "/team-logos/valencia-cf.png" },
    homeCornerAvg: 5.7,
    awayCornerAvg: 5.0,
    totalCornerAvg: 10.7,
    stadium: "Benito Villamarín",
    status: "upcoming",
    matchday: 38,
  },
  {
    id: "j38_madrid_sociedad",
    competition: "LaLiga",
    date: "25/05/2025",
    time: "21:00",
    homeTeam: { id: "real-madrid", name: "Real Madrid", logoUrl: "/team-logos/real-madrid.png" },
    awayTeam: { id: "real-sociedad", name: "Real Sociedad", logoUrl: "/team-logos/real-sociedad.png" },
    homeCornerAvg: 5.8,
    awayCornerAvg: 5.3,
    totalCornerAvg: 11.1,
    stadium: "Santiago Bernabéu",
    status: "upcoming",
    matchday: 38,
  },
  {
    id: "j38_alaves_osasuna",
    competition: "LaLiga",
    date: "25/05/2025",
    time: "18:30",
    homeTeam: { id: "alaves", name: "Deportivo Alavés", logoUrl: "/team-logos/alaves.png" },
    awayTeam: { id: "osasuna", name: "CA Osasuna", logoUrl: "/team-logos/osasuna.png" },
    homeCornerAvg: 4.9,
    awayCornerAvg: 5.4,
    totalCornerAvg: 10.3,
    stadium: "Mendizorroza",
    status: "upcoming",
    matchday: 38,
  },
  {
    id: "j38_leganes_valladolid",
    competition: "LaLiga",
    date: "25/05/2025",
    time: "18:30",
    homeTeam: { id: "leganes", name: "CD Leganés", logoUrl: "/team-logos/leganes.png" },
    awayTeam: { id: "valladolid", name: "Real Valladolid", logoUrl: "/team-logos/valladolid.png" },
    homeCornerAvg: 5.4,
    awayCornerAvg: 4.5,
    totalCornerAvg: 9.9,
    stadium: "Butarque",
    status: "upcoming",
    matchday: 38,
  },
  {
    id: "j38_espanyol_laspalmas",
    competition: "LaLiga",
    date: "25/05/2025",
    time: "18:30",
    homeTeam: { id: "espanyol", name: "RCD Espanyol", logoUrl: "/team-logos/espanyol.png" },
    awayTeam: { id: "las-palmas", name: "UD Las Palmas", logoUrl: "/team-logos/las-palmas.png" },
    homeCornerAvg: 4.9,
    awayCornerAvg: 5.2,
    totalCornerAvg: 10.1,
    stadium: "RCDE Stadium",
    status: "upcoming",
    matchday: 38,
  },
  {
    id: "j38_girona_atletico",
    competition: "LaLiga",
    date: "25/05/2025",
    time: "21:00",
    homeTeam: { id: "girona-fc", name: "Girona FC", logoUrl: "/team-logos/girona-fc.png" },
    awayTeam: { id: "atletico", name: "Atlético de Madrid", logoUrl: "/team-logos/atletico.png" },
    homeCornerAvg: 4.7,
    awayCornerAvg: 4.4,
    totalCornerAvg: 9.1,
    stadium: "Montilivi",
    status: "upcoming",
    matchday: 38,
  },
  {
    id: "j38_getafe_celta",
    competition: "LaLiga",
    date: "25/05/2025",
    time: "18:30",
    homeTeam: { id: "getafe", name: "Getafe CF", logoUrl: "/team-logos/getafe.png" },
    awayTeam: { id: "celta", name: "RC Celta de Vigo", logoUrl: "/team-logos/celta.png" },
    homeCornerAvg: 4.9,
    awayCornerAvg: 4.4,
    totalCornerAvg: 9.3,
    stadium: "Coliseum",
    status: "upcoming",
    matchday: 38,
  },
  {
    id: "j38_rayo_mallorca",
    competition: "LaLiga",
    date: "25/05/2025",
    time: "18:30",
    homeTeam: { id: "rayo", name: "Rayo Vallecano", logoUrl: "/team-logos/rayo.png" },
    awayTeam: { id: "mallorca", name: "RCD Mallorca", logoUrl: "/team-logos/mallorca.png" },
    homeCornerAvg: 5.1,
    awayCornerAvg: 5.2,
    totalCornerAvg: 10.3,
    stadium: "Vallecas",
    status: "upcoming",
    matchday: 38,
  },
  {
    id: "j38_villarreal_sevilla",
    competition: "LaLiga",
    date: "25/05/2025",
    time: "21:00",
    homeTeam: { id: "villarreal", name: "Villarreal CF", logoUrl: "/team-logos/villarreal.png" },
    awayTeam: { id: "sevilla", name: "Sevilla FC", logoUrl: "/team-logos/sevilla.png" },
    homeCornerAvg: 5.2,
    awayCornerAvg: 4.9,
    totalCornerAvg: 10.1,
    stadium: "La Cerámica",
    status: "upcoming",
    matchday: 38,
  },

  // Jornada 37
  {
    id: "j37_barcelona_rayo",
    competition: "LaLiga",
    date: "19/05/2025",
    time: "21:00",
    homeTeam: { id: "barcelona", name: "FC Barcelona", logoUrl: "/team-logos/barcelona.png" },
    awayTeam: { id: "rayo", name: "Rayo Vallecano", logoUrl: "/team-logos/rayo.png" },
    homeCornerAvg: 7.1,
    awayCornerAvg: 5.1,
    totalCornerAvg: 12.2,
    stadium: "Camp Nou",
    status: "upcoming",
    matchday: 37,
  },
  {
    id: "j37_atletico_osasuna",
    competition: "LaLiga",
    date: "19/05/2025",
    time: "18:30",
    homeTeam: { id: "atletico", name: "Atlético de Madrid", logoUrl: "/team-logos/atletico.png" },
    awayTeam: { id: "osasuna", name: "CA Osasuna", logoUrl: "/team-logos/osasuna.png" },
    homeCornerAvg: 4.4,
    awayCornerAvg: 5.4,
    totalCornerAvg: 9.8,
    stadium: "Metropolitano",
    status: "upcoming",
    matchday: 37,
  },
  {
    id: "j37_sociedad_getafe",
    competition: "LaLiga",
    date: "19/05/2025",
    time: "18:30",
    homeTeam: { id: "real-sociedad", name: "Real Sociedad", logoUrl: "/team-logos/real-sociedad.png" },
    awayTeam: { id: "getafe", name: "Getafe CF", logoUrl: "/team-logos/getafe.png" },
    homeCornerAvg: 5.3,
    awayCornerAvg: 4.9,
    totalCornerAvg: 10.2,
    stadium: "Reale Arena",
    status: "upcoming",
    matchday: 37,
  },
  {
    id: "j37_mallorca_athletic",
    competition: "LaLiga",
    date: "19/05/2025",
    time: "18:30",
    homeTeam: { id: "mallorca", name: "RCD Mallorca", logoUrl: "/team-logos/mallorca.png" },
    awayTeam: { id: "athletic-club", name: "Athletic Club", logoUrl: "/team-logos/athletic-club.png" },
    homeCornerAvg: 5.2,
    awayCornerAvg: 5.7,
    totalCornerAvg: 10.9,
    stadium: "Son Moix",
    status: "upcoming",
    matchday: 37,
  },
  {
    id: "j37_sevilla_betis",
    competition: "LaLiga",
    date: "19/05/2025",
    time: "21:00",
    homeTeam: { id: "sevilla", name: "Sevilla FC", logoUrl: "/team-logos/sevilla.png" },
    awayTeam: { id: "real-betis", name: "Real Betis", logoUrl: "/team-logos/real-betis.png" },
    homeCornerAvg: 4.9,
    awayCornerAvg: 5.7,
    totalCornerAvg: 10.6,
    stadium: "Ramón Sánchez-Pizjuán",
    status: "upcoming",
    matchday: 37,
  },
  {
    id: "j37_valencia_madrid",
    competition: "LaLiga",
    date: "19/05/2025",
    time: "21:00",
    homeTeam: { id: "valencia-cf", name: "Valencia CF", logoUrl: "/team-logos/valencia-cf.png" },
    awayTeam: { id: "real-madrid", name: "Real Madrid", logoUrl: "/team-logos/real-madrid.png" },
    homeCornerAvg: 5.0,
    awayCornerAvg: 5.8,
    totalCornerAvg: 10.8,
    stadium: "Mestalla",
    status: "upcoming",
    matchday: 37,
  },
  {
    id: "j37_valladolid_girona",
    competition: "LaLiga",
    date: "19/05/2025",
    time: "18:30",
    homeTeam: { id: "valladolid", name: "Real Valladolid", logoUrl: "/team-logos/valladolid.png" },
    awayTeam: { id: "girona-fc", name: "Girona FC", logoUrl: "/team-logos/girona-fc.png" },
    homeCornerAvg: 4.5,
    awayCornerAvg: 4.7,
    totalCornerAvg: 9.2,
    stadium: "José Zorrilla",
    status: "upcoming",
    matchday: 37,
  },
  {
    id: "j37_celta_leganes",
    competition: "LaLiga",
    date: "19/05/2025",
    time: "18:30",
    homeTeam: { id: "celta", name: "RC Celta de Vigo", logoUrl: "/team-logos/celta.png" },
    awayTeam: { id: "leganes", name: "CD Leganés", logoUrl: "/team-logos/leganes.png" },
    homeCornerAvg: 4.4,
    awayCornerAvg: 5.4,
    totalCornerAvg: 9.8,
    stadium: "Balaídos",
    status: "upcoming",
    matchday: 37,
  },
  {
    id: "j37_laspalmas_alaves",
    competition: "LaLiga",
    date: "19/05/2025",
    time: "18:30",
    homeTeam: { id: "las-palmas", name: "UD Las Palmas", logoUrl: "/team-logos/las-palmas.png" },
    awayTeam: { id: "alaves", name: "Deportivo Alavés", logoUrl: "/team-logos/alaves.png" },
    homeCornerAvg: 5.2,
    awayCornerAvg: 4.9,
    totalCornerAvg: 10.1,
    stadium: "Gran Canaria",
    status: "upcoming",
    matchday: 37,
  },
  {
    id: "j37_villarreal_espanyol",
    competition: "LaLiga",
    date: "19/05/2025",
    time: "18:30",
    homeTeam: { id: "villarreal", name: "Villarreal CF", logoUrl: "/team-logos/villarreal.png" },
    awayTeam: { id: "espanyol", name: "RCD Espanyol", logoUrl: "/team-logos/espanyol.png" },
    homeCornerAvg: 5.2,
    awayCornerAvg: 4.9,
    totalCornerAvg: 10.1,
    stadium: "La Cerámica",
    status: "upcoming",
    matchday: 37,
  },

  // Jornada 36
  {
    id: "j36_madrid_alaves",
    competition: "LaLiga",
    date: "12/05/2025",
    time: "21:00",
    homeTeam: { id: "real-madrid", name: "Real Madrid", logoUrl: "/team-logos/real-madrid.png" },
    awayTeam: { id: "alaves", name: "Deportivo Alavés", logoUrl: "/team-logos/alaves.png" },
    homeCornerAvg: 5.8,
    awayCornerAvg: 4.9,
    totalCornerAvg: 10.7,
    stadium: "Santiago Bernabéu",
    status: "upcoming",
    matchday: 36,
  },
  {
    id: "j36_athletic_sevilla",
    competition: "LaLiga",
    date: "12/05/2025",
    time: "18:30",
    homeTeam: { id: "athletic-club", name: "Athletic Club", logoUrl: "/team-logos/athletic-club.png" },
    awayTeam: { id: "sevilla", name: "Sevilla FC", logoUrl: "/team-logos/sevilla.png" },
    homeCornerAvg: 5.7,
    awayCornerAvg: 4.9,
    totalCornerAvg: 10.6,
    stadium: "San Mamés",
    status: "upcoming",
    matchday: 36,
  },
  {
    id: "j36_betis_celta",
    competition: "LaLiga",
    date: "12/05/2025",
    time: "18:30",
    homeTeam: { id: "real-betis", name: "Real Betis", logoUrl: "/team-logos/real-betis.png" },
    awayTeam: { id: "celta", name: "RC Celta de Vigo", logoUrl: "/team-logos/celta.png" },
    homeCornerAvg: 5.7,
    awayCornerAvg: 4.4,
    totalCornerAvg: 10.1,
    stadium: "Benito Villamarín",
    status: "upcoming",
    matchday: 36,
  },
]
