const teams = {
  getafe: {
    id: "getafe",
    name: "Getafe CF",
    shortName: "GET",
    logoUrl: "/team-logos/getafe.png",
  },
  celta: {
    id: "celta",
    name: "Celta de Vigo",
    shortName: "CEL",
    logoUrl: "/team-logos/celta.png",
  },
  espanyol: {
    id: "espanyol",
    name: "Espanyol",
    shortName: "ESP",
    logoUrl: "/team-logos/espanyol.png",
  },
  "las-palmas": {
    id: "las-palmas",
    name: "UD Las Palmas",
    shortName: "LPA",
    logoUrl: "/team-logos/las-palmas.png",
  },
  rayo: {
    id: "rayo",
    name: "Rayo Vallecano",
    shortName: "RAY",
    logoUrl: "/team-logos/rayo.png",
  },
  mallorca: {
    id: "mallorca",
    name: "RCD Mallorca",
    shortName: "MLL",
    logoUrl: "/team-logos/mallorca.png",
  },
  "real-betis": {
    id: "real-betis",
    name: "Real Betis",
    shortName: "BET",
    logoUrl: "/team-logos/real-betis.png",
  },
  "valencia-cf": {
    id: "valencia-cf",
    name: "Valencia CF",
    shortName: "VAL",
    logoUrl: "/team-logos/valencia-cf.png",
  },
  "real-madrid": {
    id: "real-madrid",
    name: "Real Madrid",
    shortName: "RMA",
    logoUrl: "/team-logos/real-madrid.png",
  },
  barcelona: {
    id: "barcelona",
    name: "FC Barcelona",
    shortName: "BAR",
    logoUrl: "/team-logos/barcelona.png",
  },
  "athletic-club": {
    id: "athletic-club",
    name: "Athletic Club",
    shortName: "ATH",
    logoUrl: "/team-logos/athletic-club.png",
  },
  "real-sociedad": {
    id: "real-sociedad",
    name: "Real Sociedad",
    shortName: "RSO",
    logoUrl: "/team-logos/real-sociedad.png",
  },
  atletico: {
    id: "atletico",
    name: "Atlético de Madrid",
    shortName: "ATM",
    logoUrl: "/team-logos/atletico.png",
  },
  sevilla: {
    id: "sevilla",
    name: "Sevilla FC",
    shortName: "SEV",
    logoUrl: "/team-logos/sevilla.png",
  },
  villarreal: {
    id: "villarreal",
    name: "Villarreal CF",
    shortName: "VIL",
    logoUrl: "/team-logos/villarreal.png",
  },
  alaves: {
    id: "alaves",
    name: "Deportivo Alavés",
    shortName: "ALA",
    logoUrl: "/team-logos/alaves.png",
  },
  osasuna: {
    id: "osasuna",
    name: "CA Osasuna",
    shortName: "OSA",
    logoUrl: "/team-logos/osasuna.png",
  },
  "girona-fc": {
    id: "girona-fc",
    name: "Girona FC",
    shortName: "GIR",
    logoUrl: "/team-logos/girona-fc.png",
  },
  leganes: {
    id: "leganes",
    name: "CD Leganés",
    shortName: "LEG",
    logoUrl: "/team-logos/leganes.png",
  },
  valladolid: {
    id: "valladolid",
    name: "Real Valladolid",
    shortName: "VLL",
    logoUrl: "/team-logos/valladolid.png",
  },
}

const teamStatsData = {
  getafe: {
    team: teams.getafe,
    cornersFor: 4.9,
    cornersAgainst: 4.3,
    possession: 46,
    attacks: 15,
    counterAttacks: 11,
    cornersPerMatch: 9.2,
    league: "LaLiga",
    position: 12,
    form: "WDLWD",
  },
  celta: {
    team: teams.celta,
    cornersFor: 4.4,
    cornersAgainst: 4.6,
    possession: 51,
    attacks: 17,
    counterAttacks: 9,
    cornersPerMatch: 9.0,
    league: "LaLiga",
    position: 13,
    form: "LWDLW",
  },
  espanyol: {
    team: teams.espanyol,
    cornersFor: 4.9,
    cornersAgainst: 4.7,
    possession: 48,
    attacks: 16,
    counterAttacks: 10,
    cornersPerMatch: 9.6,
    league: "LaLiga",
    position: 15,
    form: "LDWLL",
  },
  "las-palmas": {
    team: teams["las-palmas"],
    cornersFor: 5.2,
    cornersAgainst: 4.5,
    possession: 53,
    attacks: 18,
    counterAttacks: 8,
    cornersPerMatch: 9.7,
    league: "LaLiga",
    position: 16,
    form: "LWLWD",
  },
  rayo: {
    team: teams.rayo,
    cornersFor: 5.1,
    cornersAgainst: 4.8,
    possession: 49,
    attacks: 17,
    counterAttacks: 12,
    cornersPerMatch: 9.9,
    league: "LaLiga",
    position: 11,
    form: "WDLWL",
  },
  mallorca: {
    team: teams.mallorca,
    cornersFor: 5.2,
    cornersAgainst: 4.9,
    possession: 47,
    attacks: 16,
    counterAttacks: 11,
    cornersPerMatch: 10.1,
    league: "LaLiga",
    position: 14,
    form: "DLWDL",
  },
  "real-betis": {
    team: teams["real-betis"],
    cornersFor: 5.7,
    cornersAgainst: 4.2,
    possession: 58,
    attacks: 19,
    counterAttacks: 8,
    cornersPerMatch: 9.9,
    league: "LaLiga",
    position: 6,
    form: "WWDLW",
  },
  "valencia-cf": {
    team: teams["valencia-cf"],
    cornersFor: 5.0,
    cornersAgainst: 5.3,
    possession: 47,
    attacks: 16,
    counterAttacks: 12,
    cornersPerMatch: 10.3,
    league: "LaLiga",
    position: 9,
    form: "LWDLD",
  },
  "real-madrid": {
    team: teams["real-madrid"],
    cornersFor: 5.8,
    cornersAgainst: 3.5,
    possession: 62,
    attacks: 22,
    counterAttacks: 10,
    cornersPerMatch: 9.3,
    league: "LaLiga",
    position: 1,
    form: "WWWDW",
  },
  barcelona: {
    team: teams.barcelona,
    cornersFor: 7.1,
    cornersAgainst: 3.2,
    possession: 65,
    attacks: 24,
    counterAttacks: 8,
    cornersPerMatch: 10.3,
    league: "LaLiga",
    position: 2,
    form: "WWDWL",
  },
  "athletic-club": {
    team: teams["athletic-club"],
    cornersFor: 5.7,
    cornersAgainst: 4.1,
    possession: 54,
    attacks: 18,
    counterAttacks: 9,
    cornersPerMatch: 9.8,
    league: "LaLiga",
    position: 5,
    form: "WDWLW",
  },
  "real-sociedad": {
    team: teams["real-sociedad"],
    cornersFor: 5.3,
    cornersAgainst: 4.2,
    possession: 56,
    attacks: 17,
    counterAttacks: 7,
    cornersPerMatch: 9.5,
    league: "LaLiga",
    position: 7,
    form: "DWWLD",
  },
  atletico: {
    team: teams.atletico,
    cornersFor: 4.4,
    cornersAgainst: 4.1,
    possession: 52,
    attacks: 16,
    counterAttacks: 11,
    cornersPerMatch: 8.5,
    league: "LaLiga",
    position: 3,
    form: "WDWLW",
  },
  sevilla: {
    team: teams.sevilla,
    cornersFor: 4.9,
    cornersAgainst: 4.5,
    possession: 55,
    attacks: 18,
    counterAttacks: 9,
    cornersPerMatch: 9.4,
    league: "LaLiga",
    position: 8,
    form: "LWDWL",
  },
  villarreal: {
    team: teams.villarreal,
    cornersFor: 5.2,
    cornersAgainst: 4.3,
    possession: 53,
    attacks: 17,
    counterAttacks: 10,
    cornersPerMatch: 9.5,
    league: "LaLiga",
    position: 10,
    form: "WLWDL",
  },
  alaves: {
    team: teams.alaves,
    cornersFor: 4.9,
    cornersAgainst: 5.1,
    possession: 45,
    attacks: 15,
    counterAttacks: 13,
    cornersPerMatch: 10.0,
    league: "LaLiga",
    position: 17,
    form: "LDLWD",
  },
  osasuna: {
    team: teams.osasuna,
    cornersFor: 5.4,
    cornersAgainst: 4.8,
    possession: 48,
    attacks: 16,
    counterAttacks: 12,
    cornersPerMatch: 10.2,
    league: "LaLiga",
    position: 12,
    form: "LWDLL",
  },
  "girona-fc": {
    team: teams["girona-fc"],
    cornersFor: 4.7,
    cornersAgainst: 4.9,
    possession: 52,
    attacks: 17,
    counterAttacks: 9,
    cornersPerMatch: 9.6,
    league: "LaLiga",
    position: 4,
    form: "WWLWD",
  },
  leganes: {
    team: teams.leganes,
    cornersFor: 5.4,
    cornersAgainst: 4.9,
    possession: 44,
    attacks: 14,
    counterAttacks: 13,
    cornersPerMatch: 10.3,
    league: "LaLiga",
    position: 18,
    form: "LDLWL",
  },
  valladolid: {
    team: teams.valladolid,
    cornersFor: 4.5,
    cornersAgainst: 5.2,
    possession: 43,
    attacks: 13,
    counterAttacks: 12,
    cornersPerMatch: 9.7,
    league: "LaLiga",
    position: 19,
    form: "LLDLW",
  },
}

export const teamRepository = {
  getTeamById: async (id: string) => {
    console.log("Getting team by ID:", id)
    return teams[id] || null
  },

  getTeamStats: async (teamId: string) => {
    console.log("Getting team stats for:", teamId)

    // Obtener las estadísticas del equipo
    const stats = teamStatsData[teamId]
    if (!stats) {
      console.log("Stats not found for team:", teamId)
      return null
    }

    return stats
  },
}
