export const teamStatsData = {
  getafe: {
    name: "Getafe CF",
    cornersFor: 4.9,
    cornersAgainst: 4.3,
    possession: 46,
    attacks: 15,
    counterAttacks: 11,
    cornersPerMatch: 9.2,
    league: "LaLiga",
    position: 12,
    form: "WDLWD",
  },
  celta: {
    name: "Celta de Vigo",
    cornersFor: 4.4,
    cornersAgainst: 4.6,
    possession: 51,
    attacks: 17,
    counterAttacks: 9,
    cornersPerMatch: 9.0,
    league: "LaLiga",
    position: 13,
    form: "LWDLW",
  },
  espanyol: {
    name: "Espanyol",
    cornersFor: 4.9,
    cornersAgainst: 4.7,
    possession: 48,
    attacks: 16,
    counterAttacks: 10,
    cornersPerMatch: 9.6,
    league: "LaLiga",
    position: 15,
    form: "LDWLL",
  },
  "las-palmas": {
    name: "UD Las Palmas",
    cornersFor: 5.2,
    cornersAgainst: 4.5,
    possession: 53,
    attacks: 18,
    counterAttacks: 8,
    cornersPerMatch: 9.7,
    league: "LaLiga",
    position: 16,
    form: "LWLWD",
  },
  rayo: {
    name: "Rayo Vallecano",
    cornersFor: 5.1,
    cornersAgainst: 4.8,
    possession: 49,
    attacks: 17,
    counterAttacks: 12,
    cornersPerMatch: 9.9,
    league: "LaLiga",
    position: 11,
    form: "WDLWL",
  },
  mallorca: {
    name: "RCD Mallorca",
    cornersFor: 5.2,
    cornersAgainst: 4.9,
    possession: 47,
    attacks: 16,
    counterAttacks: 11,
    cornersPerMatch: 10.1,
    league: "LaLiga",
    position: 14,
    form: "DLWDL",
  },
}
